project_id = "icxjkijvlhkcsjymckfw"

[functions.socrate]
verify_jwt = false

[functions.fetch-google-doc]
verify_jwt = false

[functions.rag-engine]
verify_jwt = false

[functions.task-engine]
verify_jwt = false

[functions.dashboard-engine]
verify_jwt = false

[functions.career-engine]
verify_jwt = false

[functions.auto-sync-docs]
verify_jwt = false
