import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { Contact, Search, Mail, Building2, GraduationCap, Filter, Sparkles, Loader2, Compass } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { useApp } from "@/contexts/AppContext";
import { useSocrateSuggestions, useAffinityScores } from "@/hooks/useSocrateSuggestions";
import { useDatabaseFilter } from "@/hooks/useDatabaseFilter";

export default function ContactsPage() {
  const { profile, user, setActiveSection } = useApp();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<"all" | "supervisor" | "company" | "socrate">("all");
  const [expanded, setExpanded] = useState<string | null>(null);

  // Realtime suggestions & affinities — all data comes from DB (generated by LLM)
  const { suggestions: professorSuggestions } = useSocrateSuggestions(user?.id, ["professor"]);
  const { suggestions: companySuggestions } = useSocrateSuggestions(user?.id, ["company"]);
  const { affinities: supervisorAffinities } = useAffinityScores(user?.id, "supervisor");
  const { affinities: companyAffinities } = useAffinityScores(user?.id, "company");
  const { filterDatabase, loading: filterLoading, progress } = useDatabaseFilter();

  const allAffinities = useMemo(() => [...supervisorAffinities, ...companyAffinities], [supervisorAffinities, companyAffinities]);
  const affinityMap = useMemo(() => new Map(allAffinities.map(a => [a.entity_id, a])), [allAffinities]);

  // Build contacts from affinity_scores (LLM-generated)
  const contacts = useMemo(() => {
    return allAffinities
      .filter(a => !search || a.entity_name.toLowerCase().includes(search.toLowerCase()) || a.reasoning.toLowerCase().includes(search.toLowerCase()))
      .filter(a => filter === "all" || (filter === "supervisor" && a.entity_type === "supervisor") || (filter === "company" && a.entity_type === "company"))
      .sort((a, b) => b.score - a.score);
  }, [allAffinities, search, filter]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-accent/10"><Contact className="w-5 h-5 text-accent" /></div>
          <div>
            <h1 className="text-xl font-bold font-display">Rubrica Contatti</h1>
            <p className="text-sm text-muted-foreground">{supervisorAffinities.length} professori · {companyAffinities.length} aziende</p>
          </div>
        </div>
        <Button onClick={filterDatabase} disabled={filterLoading} variant="outline" size="sm" className="gap-1.5">
          {filterLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5 text-ai" />}
          {filterLoading ? "Generating..." : "Genera con Socrate"}
        </Button>
      </div>

      {/* Empty state */}
      {allAffinities.length === 0 && !filterLoading && (
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
          className="bg-card border border-dashed rounded-xl p-8 text-center">
          <Sparkles className="w-10 h-10 text-muted-foreground mx-auto mb-3" />
          <p className="text-sm font-medium text-foreground mb-1">Nessun contatto ancora</p>
          <p className="text-xs text-muted-foreground mb-4">
            Clicca "Genera con Socrate" per ricevere raccomandazioni personalizzate di professori e aziende basate sulla tua tesi.
          </p>
          <Button onClick={filterDatabase} disabled={filterLoading} size="sm" className="gap-1.5">
            <Sparkles className="w-3.5 h-3.5" /> Genera Raccomandazioni
          </Button>
        </motion.div>
      )}

      {allAffinities.length > 0 && (
        <>
          {/* Search + Filters */}
          <div className="space-y-2">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Cerca per nome, competenza..."
                className="w-full bg-card border rounded-lg pl-10 pr-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-accent" />
            </div>
            <div className="flex gap-2 flex-wrap items-center">
              <Filter className="w-3.5 h-3.5 text-muted-foreground" />
              {([
                { v: "all", l: `Tutti (${allAffinities.length})` },
                { v: "supervisor", l: `Professori (${supervisorAffinities.length})` },
                { v: "company", l: `Aziende (${companyAffinities.length})` },
              ] as const).map(opt => (
                <button key={opt.v} onClick={() => setFilter(opt.v as any)}
                  className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${filter === opt.v ? "bg-accent text-accent-foreground" : "bg-muted text-muted-foreground hover:text-foreground"}`}>
                  {opt.l}
                </button>
              ))}
            </div>
          </div>

          {/* Contacts Grid */}
          <div className="grid gap-3">
            {contacts.map((contact, i) => {
              const isExpanded = expanded === contact.entity_id;
              return (
                <motion.div key={contact.entity_id} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.02 }}
                  className="bg-card border border-ai/20 rounded-xl shadow-sm hover:shadow-md transition-all cursor-pointer"
                  onClick={() => setExpanded(isExpanded ? null : contact.entity_id)}>
                  <div className="flex items-center gap-4 p-4">
                    <div className={`w-11 h-11 rounded-full flex items-center justify-center shrink-0 ${contact.entity_type === "supervisor" ? "bg-accent/10 text-accent" : "bg-success/10 text-success"}`}>
                      {contact.entity_type === "supervisor" ? <GraduationCap className="w-5 h-5" /> : <Building2 className="w-5 h-5" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <h3 className="font-semibold text-sm truncate">{contact.entity_name}</h3>
                        <span className="text-xs font-bold text-ai shrink-0">{contact.score}%</span>
                        {contact.matched_traits?.includes("exploration") && (
                          <Badge variant="secondary" className="text-[9px] bg-warning/10 text-warning border-0 shrink-0">
                            <Compass className="w-2.5 h-2.5 mr-0.5 inline" />Esplora
                          </Badge>
                        )}
                        <Badge variant={contact.entity_type === "supervisor" ? "default" : "secondary"} className="text-[10px] shrink-0">
                          {contact.entity_type === "supervisor" ? "Prof" : "Azienda"}
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground truncate">{contact.reasoning}</p>
                    </div>
                  </div>
                  {isExpanded && (
                    <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }}
                      className="px-4 pb-4 border-t border-border pt-3 space-y-2">
                      <div className="bg-ai/5 border border-ai/10 rounded-lg p-3">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-[10px] font-medium text-ai">Affinità Socrate</span>
                          <span className="text-sm font-bold text-ai">{contact.score}%</span>
                        </div>
                        <Progress value={contact.score} className="h-1 mb-2" />
                        <p className="text-xs text-muted-foreground italic">{contact.reasoning}</p>
                        {contact.matched_traits?.length > 0 && (
                          <div className="flex flex-wrap gap-1 mt-1.5">
                            {(contact.matched_traits as string[]).map((t, j) => (
                              <span key={j} className="text-[9px] px-1.5 py-0.5 rounded bg-ai/10 text-ai">{t}</span>
                            ))}
                          </div>
                        )}
                      </div>
                    </motion.div>
                  )}
                </motion.div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
