
-- Socrate tasks: personalized tasks generated by AI
CREATE TABLE public.socrate_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  section TEXT NOT NULL, -- thesis section or topic area
  priority TEXT NOT NULL DEFAULT 'medium', -- critical, high, medium, low
  estimated_minutes INTEGER DEFAULT 30,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, in_progress, completed, dismissed
  source TEXT DEFAULT 'socrate', -- socrate, latex_analysis, fusion
  created_at TIMESTAMPTZ DEFAULT now(),
  completed_at TIMESTAMPTZ
);

ALTER TABLE public.socrate_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own tasks" ON public.socrate_tasks FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Users insert own tasks" ON public.socrate_tasks FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users update own tasks" ON public.socrate_tasks FOR UPDATE TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Users delete own tasks" ON public.socrate_tasks FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE INDEX idx_socrate_tasks_user ON public.socrate_tasks(user_id, status, created_at DESC);

ALTER PUBLICATION supabase_realtime ADD TABLE public.socrate_tasks;
